# Generated by Django 4.1.2 on 2022-11-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('urgent', 'Urgent'), ('pending', 'Pending')], default='active', max_length=50)),
                ('admin_email', models.CharField(default='', max_length=55, verbose_name='Contact Email')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, upload_to='client-media/')),
                ('phone', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='staff-media/default.jpg', upload_to='staff-media/')),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('development', 'Development'), ('management', 'Management')], max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('blog', 'Blog'), ('video', 'Video'), ('facebook_image', 'Facebook Image Post'), ('facebook_carasel', 'Facebook Carasel Post'), ('instagram_image', 'Instagram Post'), ('instagram_reel', 'Instagram Reel'), ('instagram_story', 'Instagram Story Post'), ('linkedin_post', 'Linkedin Post'), ('twitter_post', 'Twitter Post')], default='facebook_image', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=25)),
                ('image_1', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_2', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_3', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_4', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_5', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_6', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_7', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_8', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_9', models.ImageField(blank=True, upload_to='post-media/')),
                ('image_10', models.ImageField(blank=True, upload_to='post-media/')),
                ('video_file', models.FileField(blank=True, upload_to='post-media/')),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=200, null=True, unique=True)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='content.companyprofile')),
                ('staff', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='content.companyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.companyprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
