# Generated by Django 4.1.2 on 2022-11-10 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('video', 'Video'), ('facebook_image', 'Facebook Image Post'), ('facebook_carasel', 'Facebook Carasel Post'), ('instagram_image', 'Instagram Post'), ('instagram_reel', 'Instagram Reel'), ('instagram_story', 'Instagram Story Post'), ('linkedin_post', 'Linkedin Post'), ('twitter_post', 'Twitter Post')], default='facebook_image', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending_customer_review', 'Pending Customer Review'), ('pending_customer_revision', 'Pending Customer Revision'), ('published', 'Published'), ('in_design', 'In Design'), ('approved', 'Approved')], default='draft', max_length=25),
        ),
    ]
