# Generated by Django 4.1.2 on 2022-11-11 22:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_first_name', models.CharField(default='', max_length=35, verbose_name='Contact First Name')),
                ('admin_last_name', models.CharField(default='', max_length=35, verbose_name='Contact Last Name')),
                ('admin_email', models.CharField(default='', max_length=55, verbose_name='Contact Email')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, upload_to='client-media/')),
                ('phone', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=uuid.uuid1, max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='staff-media/')),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('development', 'Development'), ('management', 'Management')], max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='client',
        ),
        migrations.RemoveField(
            model_name='post',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.user',),
            managers=[
                ('client', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.user',),
            managers=[
                ('staff', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
