# Generated by Django 4.1.2 on 2022-11-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_client_user_alter_post_post_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
