# Generated by Django 4.1.2 on 2022-11-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_post_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
