# Generated by Django 4.1.2 on 2022-11-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_clientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='admin_first_name',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='admin_last_name',
        ),
    ]
