# Generated by Django 4.1.2 on 2022-11-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_email',
            field=models.CharField(default='Contact Email', max_length=55, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='admin_name',
            field=models.CharField(default='Contact Name', max_length=35, verbose_name='Contact'),
        ),
    ]
