# Generated by Django 4.1.2 on 2022-11-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_companyprofile_admin_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('urgent', 'Urgent'), ('pending', 'Pending')], default='active', max_length=50),
        ),
    ]
