# Generated by Django 4.1.2 on 2022-11-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_client_slug_alter_client_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='', max_length=200, null=True, unique=True),
        ),
    ]
