# Generated by Django 4.1.2 on 2022-11-11 00:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=200, null=True, unique=True),
        ),
    ]
