# Generated by Django 4.1.2 on 2022-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_postrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrevision',
            name='image',
            field=models.IntegerField(default=1),
        ),
    ]
